#!/bin/bash
mkdir ISMS
cd ISMS 
echo "1, All ursers" > $USER.txt
echo "-------------" >> $USER.txt
dscl . list /Users | grep -v "^_" >> $USER.txt
echo "=============" >> $USER.txt
echo >> $USER.txt
echo
echo "2, all application"
echo "-------------"
#find / -iname *.app > applications.txt
echo "============="
echo >> $USER.txt
echo
echo "3, filevault" >> $USER.txt
echo "-------------" >> $USER.txt
fdesetup status >> $USER.txt
echo "=============" >> $USER.txt
echo >> $USER.txt
echo
echo "4, icloud" >> $USER.txt
echo "-------------" >> $USER.txt
defaults read MobileMeAccounts Accounts >> $USER.txt
echo "=============" >> $USER.txt
echo >> $USER.txt
echo
echo "7, security updated" >> $USER.txt
echo "-------------" >> $USER.txt
system_profiler SPInstallHistoryDataType | grep "Security Update" >> $USER.txt
echo "=============" >> $USER.txt
echo >> $USER.txt
echo
echo "8, chrome history"
echo "-------------"
Hihi=($(dscl . list /Users | grep -v "^_"))
for str in ${Hihi[@]}; do
  cp "/Users/$str/Library/Application Support/Google/Chrome/Default/History" chrome_history_$str
  sqlite3 -header -csv chrome_history_$str "select * from downloads;" > chrome_downloaded_$str.csv
  sqlite3 -header -csv chrome_history_$str "select * from urls;" > chrome_urls_$str.csv
done
echo "============="
echo
